### PR TITLE
[WIP] Cleanup codebase

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This is highly WIP, so please do not merge.

This is a full overhaul of the codebase. I will clean up _everything_ but not change functionality!

A functionality-cleanup will follow after this is merged.
We can argue on things (if we keep the discussion calm), of course.

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
One thing I'd like to have your opinion on:

I really dislike `typedef`s. They hide information about what the variable actually is. I'd like to remove all typedefs in the project.

A point where typedefs make sense: If you have something like:

```C
#ifdef FOO
typedef struct foo Foo;
#else
typedef struct bar Foo;
#end
```

But it makes no sense to hide information of normal types like this:

```C
typedef struct _foo foo;
```

If you do something like the above, you could also do:

```C
typedef int Number
```

And nobody knows what exactly is there behind the `Number` thingy. Is it a `int`, `float`, `double` or even a `struct { int a; int b; float c; }` or maybe a `enum`?

Opinions?

**Comment by matthiasbeyer** [comment]
I'm working on removing typedefs right now and I guess I will add the commits to this PR today.

If possible, please do not merge any other PRs before I'm done, because this would make rebasing my stuff a bit painful...

**Comment by matthiasbeyer** [comment]
There are things left which could be done, but I guess this is ready for a first review.

**Comment by lharding** [comment]
There's a lot here! I'll review it as soon as I have a chance but wanted to dash off some quick thoughts:

For typedefs, my pretentious opinion is that they're useful if they:
1. convey semantic information about the variable's content
2. said semantic information adds more utility than that removed by the obscuring of the underlying data type
3. allow the type checker to help verify correct use

Of course #3 is a little dubious in C, so it's really down to #1 and #2 here. I can't be sure until I have time for a detail review, but it looks like we're on the same page with their use here.

**Pull request merged**
